var country_to_adjectival = {
  "Afghanistan": "Afghan",
  "Albania": "Albanian",
  "Algeria": "Algerian",
  "Angola": "Angolan",
  "Antigua": "Antiguan",
  "Barbuda": "Antiguan",
  "Argentina": "Argentine",
  "Armenia": "Armenian",
  "Australia": "Australian",
  "Austria": "Austrian",
  "Azerbaijan": "Azerbaijan",
  "Bahamas": "Bahamian",
  "Bahrain": "Bahrain",
  "Bangladesh": "Bangladesh",
  "Barbados": "Barbados",
  "Belarus": "Belarussian",
  "Belgium": "Belgian",
  "Belize": "Belize",
  "Benin": "Beninese",
  "Bhutan": "Bhutanese",
  "Bolivia": "Bolivian",
  "Bosnia": "Bosnian",
  "Herzegovina": "Bosnian",
  "Botswana": "Botswana",
  "Brazil": "Brazilian",
  "Brunei Darussalam": "Brunei",
  "Bulgaria": "Bulgarian",
  "Burkina Faso": "Burkinabe",
  "Burundi": "Burundi",
  "Cambodia": "Cambodian",
  "Cameroon": "Cameroonian",
  "Canada": "Canadian",
  "Cape Verde": "Cape Verdean",
  "Central African Republic": "Central African",
  "Chad": "Chadian",
  "Chile": "Chilean",
  "China": "Chinese",
  "Colombia": "Colombian",
  "Comoros": "Comorian",
  "Congo, Democratic Republic of": "Congolese",
  "Congo, Republic of the": "Congolese",
  "Costa Rica": "Costa Rican",
  "Côte d'Ivoire": "Ivorian",
  "Croatia": "Croatian",
  "Cuba": "Cuban",
  "Cyprus": "Cypriot",
  "Czech Republic": "Czech",
  "Denmark": "Danish",
  "Djibouti": "Djibouti",
  "Dominica": "Dominica",
  "Dominican Republic": "Dominican",
  "Ecuador": "Ecuadoran",
  "Egypt": "Egyptian",
  "El Salvador": "Salvadoran",
  "Equatorial Guinea": "Equatorial Guinean",
  "Eritrea": "Eritrean",
  "Estonia": "Estonian",
  "Ethiopia": "Ethiopian",
  "Fiji": "Fiji",
  "Finland": "Finnish",
  "France": "French",
  "Gabon": "Gabonese",
  "Gambia": "Gambian",
  "Georgia": "Georgian",
  "Germany": "German",
  "Ghana": "Ghanaian",
  "Greece": "Greek",
  "Grenada": "Grenadian",
  "Guatemala": "Guatemalan",
  "Guinea": "Guinean",
  "Guinea-Bissau": "Guinea-Bissau",
  "Guyana": "Guyanese",
  "Haiti": "Haitian",
  "Honduras": "Honduran",
  "Hungary": "Hungarian",
  "Iceland": "Icelandic",
  "India": "Indian",
  "Indonesia": "Indonesian",
  "Iran, Islamic Republic of": "Iranian",
  "Iraq": "Iraqi",
  "Ireland": "Irish",
  "Israel": "Israeli",
  "Italy": "Italian",
  "Jamaica": "Jamaican",
  "Japan": "Japanese",
  "Jordan": "Jordanian",
  "Kazakhstan": "Kazakhstani",
  "Kenya": "Kenyan",
  "Kiribati": "Kiribati",
  "South Korea": "South Korean",
  "North Korea": "North Korean",
  "Kuwait": "Kuwaiti",
  "Kyrgyzstan": "Kyrgyz",
  "Laos": "Lao",
  "Latvia": "Latvian",
  "Lebanon": "Lebanese",
  "Lesotho": "Lesotho",
  "Liberia": "Liberian",
  "Libya": "Libyan",
  "Lithuania": "Lithuanian",
  "Luxembourg": "Luxembourg",
  "Macedonia": "Macedonian",
  "Madagascar": "Malagasy",
  "Malawi": "Malawian",
  "Malaysia": "Malaysian",
  "Maldives": "Maldivian",
  "Mali": "Malian",
  "Malta": "Maltese",
  "Marshall Islands": "Marshall Islands",
  "Mauritania": "Mauritanian",
  "Mauritius": "Mauritian",
  "Mexico": "Mexican",
  "Federated States of Micronesia": "Micronesian",
  "Moldova": "Moldovan",
  "Mongolia": "Mongolian",
  "Morocco": "Moroccan",
  "Mozambique": "Mozambican",
  "Myanmar": "Myanmar",
  "Namibia": "Namibian",
  "Nepal": "Nepalese",
  "Netherlands": "Dutch",
  "New Zealand": "New Zealand",
  "Nicaragua": "Nicaraguan",
  "Niger": "Nigerien",
  "Nigeria": "Nigerian",
  "Norway": "Norwegian",
  "Oman": "Omani",
  "Pakistan": "Pakistani",
  "Palau": "Palauan",
  "Panama": "Panamanian",
  "Papua New Guinea": "Papua New Guinea",
  "Paraguay": "Paraguayan",
  "Peru": "Peruvian",
  "Philippines": "Philippine",
  "Poland": "Polish",
  "Portugal": "Portuguese",
  "Qatar": "Qatar",
  "Romania": "Romanian",
  "Russian Federation": "Russian",
  "Rwanda": "Rwandese",
  "Samoa": "Samoan",
  "San Marino": "Sammarinese",
  "Saudi Arabia": "Saudi Arabian",
  "Senegal": "Senegalese",
  "Seychelles": "Seychelles",
  "Sierra Leone": "Sierra Leonean",
  "Singapore": "Singaporean",
  "Slovak Republic": "Slovak",
  "Slovenia": "Slovenian",
  "Solomon Islands": "Solomon Islands",
  "Somalia": "Somali",
  "South Africa": "South African",
  "Spain": "Spanish",
  "Sri Lanka": "Sri Lanka",
  "St. Kitts and Nevis": "St. Kitts and Nevis",
  "St. Lucia": "St. Lucian",
  "St. Vincent and the Grenadines": "Vincentian",
  "Sudan": "Sudanese",
  "Suriname": "Surinamese",
  "Swaziland": "Swazi",
  "Sweden": "Swedish",
  "Switzerland": "Swiss",
  "Syrian Arab Republic": "Syrian",
  "Tajikistan": "Tajik",
  "Tanzania": "Tanzanian",
  "Thailand": "Thai",
  "Togo": "Togolese",
  "Tonga": "Tongan",
  "Tunisia": "Tunisian",
  "Turkey": "Turkish",
  "Turkmenistan": "Turkmen",
  "Uganda": "Ugandan",
  "Ukraine": "Ukrainian",
  "United Arab Emirates": "United Arab Emirates",
  "United Kingdom": "British",
  "United States": "United States",
  "Uruguay": "Uruguayan",
  "Uzbekistan": "Uzbek",
  "Vanuatu": "Vanuatu",
  "Venezuela": "Venezuelan",
  "Vietnam": "Vietnamese",
  "Yemen": "Yemeni",
  "Zambia": "Zambian",
  "Zimbabwe": "Zimbabwean",
}